# Generated by Django 3.2.5 on 2021-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, unique=True, upload_to='documentos', verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='classe',
            field=models.CharField(blank=True, choices=[('12', '12'), ('10', '10')], max_length=100, verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='disciplina',
            field=models.CharField(choices=[('matematica', 'matematica'), ('fisica', 'fisica'), ('geografia', 'geografia'), ('portugues', 'portugues'), ('english', 'english'), ('quimica', 'quimica'), ('filosofia', 'filosofia'), ('desenho', 'desenho')], max_length=100, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='instituicao',
            field=models.CharField(choices=[('UEM', 'Universidade Eduardo Mondlane'), ('UP', 'Universidade Pedagógica'), ('UJC', 'Univeridade Jaoquim Chissano'), ('IFP', 'IFP'), ('ICISA', 'ICISA'), ('Outra', 'Outra'), ('escolar', 'escolar'), ('ETP', 'ETP')], max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='nivel',
            field=models.CharField(choices=[('medio', 'medio'), ('superior', 'superior'), ('escolar', 'escolar')], max_length=100, verbose_name='Nivel'),
        ),
    ]
