# Generated by Django 3.2.5 on 2021-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0003_alter_exame_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.CharField(blank=True, max_length=300, verbose_name='Texto do documento'),
        ),
    ]
