# Generated by Django 3.2.5 on 2021-08-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0004_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.FileField(upload_to='imagem', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(unique=True, upload_to='documentos', verbose_name='documento'),
        ),
    ]
