# Generated by Django 3.2.5 on 2021-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0005_auto_20210814_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.FileField(blank=True, upload_to='imagem', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, unique=True, upload_to='documentos', verbose_name='documento'),
        ),
    ]
