# Generated by Django 3.2.5 on 2021-08-16 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0007_auto_20210816_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to='documentos', verbose_name='doc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.CharField(blank=True, max_length=300, verbose_name='texto do doc'),
        ),
    ]
